### ISSUE TITLE
how to disable inline query

### ISSUE THREAD

**Issue by JayceCao** [brookhong/Surfingkeys#1052]
When I  choose some text with mouse in a web page, the plugin will open https://github.com/brookhong/Surfingkeys/wiki/Register-inline-query automatically. How do I disable this? It's too annoying

**Comment by brookhong** [comment]
`;q` to toggle mouseSelectToQuery.

**Comment by Stvad** [comment]
I've also hit this. It's very annoying and confusing. There should be an indication that this is what happening/more of a notification when it's being enabled. Or maybe it should not do anything (vs jumping to the help page) if not configured

**Comment by imLogM** [comment]
@brookhong 

I've also hit this. 
When I use mouse to select a text in Google Search Box, it leads me to 
 a wiki page: https://github.com/brookhong/Surfingkeys/wiki/Register-inline-query  
Now I know it is because I open "mouseSelectToQuery" involuntary. 
Maybe you can write a guide in that wiki page about how to close mouseSelectToQuery.

我也遇到了这个问题。当我使用鼠标选中Google搜索框中的文本时，浏览器会跳转到一个wiki页面。
那个wiki页面介绍了如何自定义query网址，但没提到这是个可以通过按键开启或关闭的功能。直到我搜了搜 issue 才发现是因为我无意中开启了 "mouseSelectToQuery" 。
建议作者可以在那个wiki页面上写一下"如何关闭mouseSelectToQuery"。因为大部分用户不容易发现这个功能可以开启和关闭，遇到问题时也不一定会搜索 issue。

**Comment by drk-mtr** [comment]
I've been back to the issues page about 7 times to find out the keys to turn this back off. You could say it's not my favourite feature ha.

**Comment by arizzubair** [comment]
For me `vunmap("q")` worked. Pressing `q` triggers the inline query in visual mode. While you are at it you can also unmap `Q`.
