### ISSUE TITLE
YouTube网页回弹

### ISSUE THREAD

**Issue by kalarita** [brookhong/Surfingkeys#1055]
在YouTube网页上在开启该插件时移动鼠标会造成网页回弹现象,移动一次回弹一点距离,已经尝试之开启部分快捷键和在YouTube网页禁用但是网页还是回弹,vimium不会有这个问题.
另:应该是在26号的更新之后出现的问题

**Comment by rovo98** [comment]
The same behavior can be seen on other web sites, especially video sites where the scrollbar automatically rolls back when you move down a little bit. The problem is gone after turning off this extension in chrome's extension manager.
>>>
在其他的网站也会出现同样的情况，视频网站比较明显。当你向下滚动一点距离后，滚动条会向上自动回滚一段距离。关闭该扩展程序后，问题消失。

**Comment by brookhong** [comment]
能录个视频说明下问题现象吗？

**Comment by kalarita** [comment]
> 能录个视频说明下问题现象吗？

https://drive.google.com/open?id=1O6Fje-VR9iLwrt1S645yddp39QaP_qlE
大概就是视频里面这个样子,之前通过开关每一个插件确定是这个插件的问题,晚上可能网络条件不太好,但是之前白天测试的时候也会出现这个问题,所以大概可以排除网络原因造成的网页加载不顺畅

**Comment by skaniol** [comment]
I think this might be related to the page zoom. Personally, I use 150% default zoom on my browsers. If I try anything but 100% zoom, this problem occurs.  

On my end it's very easy to reproduce. Just use a custom zoom and enter VISUAL mode. Every movement of the cursor causes the page to scroll up a little. On Youtube it also happens when you hover the mouse over a video thumbnail.  

My main other problem on Youtube is how holding `"j"` or `"k"` causes the keys to pass through resulting in multiple rewinds/pauses of the video. This is probably unrelated, but extremely annoying when it happens. Looks like the extension can't handle all keys and they leak.

**Comment by kalarita** [comment]
同样的问题出现在bilibili和爱奇艺

**Comment by rovo98** [comment]
> 能录个视频说明下问题现象吗？

https://drive.google.com/open?id=1O2pe0B5LKeUHihP8ZriRKNpmHqCm0Bae

简单复原了一下，浏览一些网站时，滚动会出现轻微卡顿（例如，知乎，在滚动内容列表时出现轻微回弹，还有其他的网站，如youtube）

浏览一些视频网站时，鼠标向下滑动或快捷键 d, j 向下时，滚动条出现明显回滚现象，例如：youku, bilibili

遇到类似问题的视频网站中，最明显的是bilibili， 几乎任何视频播放页面（无论新旧版本）。youku的话，我测试到的是一个播放一开始时在播放广告的视频 (在该视频播放广告结束后，问题似乎消失)。

**Comment by brookhong** [comment]
Thanks @skaniol 

I can reproduce this issue after zoom in a page on Mac. The other issue you're talking should be the one here https://github.com/brookhong/Surfingkeys/issues/425, what's your OS? 

@kalarita @rovo98 你们是在什么系统下？是否也放大或缩小了页面？

**Comment by rovo98** [comment]
> Thanks @skaniol
> 
> I can reproduce this issue after zoom in a page on Mac. The other issue you're talking should be the one here #425, what's your OS?
> 
> @kalarita @rovo98 你们是在什么系统下？是否也放大或缩小了页面？

manjaro linux  chrome  页面无缩放 (100%)

**Comment by kalarita** [comment]
> Thanks @skaniol
> 
> I can reproduce this issue after zoom in a page on Mac. The other issue you're talking should be the one here #425, what's your OS?
> 
> @kalarita @rovo98 你们是在什么系统下？是否也放大或缩小了页面？

Windows 10 chrome 页面无缩放

**Comment by rovo98** [comment]
> > Thanks @skaniol
> > I can reproduce this issue after zoom in a page on Mac. The other issue you're talking should be the one here #425, what's your OS?
> > @kalarita @rovo98 你们是在什么系统下？是否也放大或缩小了页面？
> 
> manjaro linux chrome 页面无缩放 (100%)

chrome stable 78.0.3904.70-1

**Comment by brookhong** [comment]
刚发了个新版0.9.50，你们试试有没有解决问题？我在mac上缩放的情况下已解决。

**Comment by rovo98** [comment]
> 刚发了个新版0.9.50，你们试试有没有解决问题？我在mac上缩放的情况下已解决。

已解决，非常感谢😊

**Comment by skaniol** [comment]
> The other issue you're talking should be the one here #425, what's your OS?  

Yes, the other issue seems to be the one you linked. I gave my details there.  

This one appears to be fixed for me, since I can't reproduce it anymore.

**Comment by kalarita** [comment]
> 刚发了个新版0.9.50，你们试试有没有解决问题？我在mac上缩放的情况下已解决。
已解决,感谢

**Comment by aliveupstairs** [comment]
Video:
[![image](https://user-images.githubusercontent.com/46059092/76655981-df934500-656e-11ea-997a-269f7e993c01.png)](https://i.imgur.com/0CK11yd.mp4)
