### ISSUE TITLE
<div id="sk_frame"/>，这个div的样式有个花花绿绿的框，在我打开某些页面的时候会被加载出来

### ISSUE THREAD

**Issue by goddess0910** [brookhong/Surfingkeys#1057]
[截图](http://ww1.sinaimg.cn/large/006cqKYCly1g8dqhecuk7j31co0i50wi.jpg)

<div id="sk_frame"/>，这个div的样式有个花花绿绿的框，在我打开某些页面的时候会被加载出来
如图，我打断点截到这张图。这个样式会一闪而过，希望能够解决

[您的源码](https://github.com/brookhong/Surfingkeys/blob/ce5c9321700780f1908b83e3578c6a5e5d514ee1/content_scripts/front.js#L129)

我不太擅长提issue，还请见谅

**Comment by brookhong** [comment]
这个框是用来提示用户当前scroll target。

**Comment by goddess0910** [comment]
有配置项可以禁止掉这个吗，谢谢

**Comment by anhnhoktvn** [comment]
I have same problem with <div id="sk_frame">, some sites (discord, some localhost dev site) don't have iframe but it's still have this highlight. I think this is a bug.

**Comment by goddess0910** [comment]
C:\Users\UserName\AppData\Local\Google\Chrome\User Data\Default\Extensions\gfbliohnnapiefjpjlpjnehglfpaknnc
它的源码在这个文件夹下，我直接修改了0.9.50/content_scripts/front.js。这个文件中highlightElement函数，直接return或者注释掉。再将此文件夹重新拖至chrome://extensions/谷歌插件下，他虽然告诉我有错误但是我任然正常运行了。这个scroll target 也不再出现

**Comment by anhnhoktvn** [comment]
@goddess0910 , if you really want to disable this feature you can comment out this line:
[https://github.com/brookhong/Surfingkeys/blob/ce5c9321700780f1908b83e3578c6a5e5d514ee1/content_scripts/front.js#L132](https://github.com/brookhong/Surfingkeys/blob/ce5c9321700780f1908b83e3578c6a5e5d514ee1/content_scripts/front.js#L132)

Because it's minified when packed, you should look for something like this:
```
    (i.highlightElement = function(e) {
      // document.body.append(d) <-- here you are
      var n = e.rect
      ;(d.style.top = n.top + 'px'),
        (d.style.left = n.left + 'px'),
        (d.style.width = n.width + 'px'),
        (d.style.height = n.height + 'px'),
        (d.style.display = ''),
        setTimeout(function() {
          d.remove()
        }, e.duration)
```
