### ISSUE TITLE
Mastodon textarea doesn't update when edited with <CTRL-i>

### ISSUE THREAD

**Issue by celfred** [brookhong/Surfingkeys#1178]
Hello,
I'm on Firefox 74 on Ubuntu 16.04.
I use Mastodon and noticed that the textarea in which you type messages does not update whe editing it with <CTRL-i>. I get the vim-like editor and when I enter :wq it closes but the textarea stays empty and I lose my text :disappointed: 

I feel strange I'm the only one... Maybe I don't use it well.

**Comment by brookhong** [comment]
Some textarea / input on some sites can not be updated because the sites have their own js code to populate data. It is impossible for extension to manipulate internal data of those input elements.

You can try my custom build of Chromium, which implements an experimental DOM API for such case. Please refer to
1. https://github.com/brookhong/Surfingkeys/commit/cf905bbfabeef967f3bfa30d643ced9e9ba82827
2. https://brookhong.github.io/2021/04/18/brook-build-of-chromium.html

**Comment by celfred** [comment]
Thanks for the explanation :+1:
