### ISSUE TITLE
屏幕滚动问题

### ISSUE THREAD

**Issue by iwestlin** [brookhong/Surfingkeys#119]
在一些站点（比如https://www.zhihu.com/）
打开页面后如果不用鼠标或触控板滚动屏幕，直接按d/e/j/k/gg/G等键，屏幕不会滚动。但如果用鼠标或触控板先滚动过，那么快捷键滚动也能用了。不知道是否只有我遇到这种情况？
环境：macOS，chrome版本 53.0.2785.143 (64-bit)
看了下源码normal.js，太难懂……

**Comment by brookhong** [comment]
当网页焦点被某些frame拿走了，会出现你这样的问题，你可以按`w`把焦点切回你需要的frame.

**Comment by iwestlin** [comment]
@brookhong 试过了，w/cs都试过，焦点确实是在主页面上，按d的时候会出现滚动条，但就是不滚动。

**Comment by iwestlin** [comment]
按键盘⬆️和⬇️可以滚动，然后就可以按d/e/gg/G/j/k了，但是一开始就按d/e...都不滚动。

**Comment by brookhong** [comment]
试试这有人提到的方法，如果大家能用英文提问会更好。https://github.com/brookhong/Surfingkeys/issues/117

**Comment by iwestlin** [comment]
试过了，还是老样子……
我觉得可能只有我遇到这个问题，不具有普遍性，所以直接用中文了。我开的另一个[issue](https://github.com/brookhong/Surfingkeys/issues/118)应该大家都会遇到，所以用的英文。

另外我英文表达比较费劲- -

**Comment by zhongkeli** [comment]
I also meet this issue. I cannot scroll correctly using the navigation keys (J,k.l,d, etc.) until I press the space bar a couple of times in www.baidu.com. Also, this issue is still not been fixed by following the instruction in [117](https://github.com/brookhong/Surfingkeys/issues/117). Could you help take a look

**Comment by brookhong** [comment]
I had had this issue after mac OS  upgraded to sierra(10.12.2).

0.6.8 should have fixed this issue, feel free to reopen this if you still have problem on scrolling.
