### ISSUE TITLE
Cannot navigate Google properly, too many links and get to cached version of website

### ISSUE THREAD

**Issue by tylerwolf35** [brookhong/Surfingkeys#1197]
## Prelude
* Could you find answer in below documents?

    1. [FAQ](https://github.com/brookhong/Surfingkeys/wiki/FAQ) / [常见问题](https://github.com/brookhong/Surfingkeys/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
    1. [README](https://github.com/brookhong/Surfingkeys/blob/master/README.md) / [读我](https://github.com/brookhong/Surfingkeys/blob/master/README_CN.md)

No

* Have you searched your problem in [issues](https://github.com/brookhong/Surfingkeys/issues)?

Yes

## Error details

<--! **You can simply click dropdown menu from Surfingkeys' icon in toolbar, which will provide necessary info.**
![image](https://user-images.githubusercontent.com/288207/39614555-6048977e-4fa3-11e8-8476-46203af7c4d6.png) -->

SurfingKeys: 0.9.60

Browser: Firefox 75.0

URL: https://google.com

## Context

**I am having issues when it comes to using SurfingKeys while searching with the Google search engine. There are too many links that I can press using the key search and many times when I attempt to click it I get redirected to the cached version of the site. This is not an issue when using Vimium.**

**Comment by max-sixty** [comment]
Here's a repro of this — which link goes to the site? 

Though potentially already fixed in an unreleased version by hiding one of them? Might it be possible to differentiate between the arrow and the link by, say, a different color? 

<img width="633" alt="image" src="https://user-images.githubusercontent.com/5635139/79245410-e8588e80-7e2c-11ea-996b-8335b920f318.png">
