### ISSUE TITLE
open in non-active tab (`gf`, `C`) and open multiple links (`cf`) are missing link hints compared to `f`

### ISSUE THREAD

**Issue by vogler** [brookhong/Surfingkeys#1221]
SurfingKeys: 0.9.63
Browser: Chrome 81.0.4044.122
URL: https://www.golem.de/

## Context
On some websites (e.g. https://www.golem.de), `gf` and `C` do not show all link hints, wheras `f` and `cf` do. I would expect them to behave the same.

Example for `f` which shows hints for the images and titles:
![image](https://user-images.githubusercontent.com/493741/80729040-fa624e80-8b07-11ea-9701-596d9878cba1.png)
and `C` which is missing those hints:
![image](https://user-images.githubusercontent.com/493741/80729132-149c2c80-8b08-11ea-801e-c34d1d6909e7.png)

**Comment by alexalekseyenko** [comment]
`createHintsForClick` is defined such that, when `tabbed` is not set to `true`, a different method is used for finding candidate elements:
https://github.com/brookhong/Surfingkeys/blob/fa10d12b9a03dcdf9f6bdcc0860ffa8545f9552a/content_scripts/hints.js#L348-L370
and neither 'cf:
https://github.com/brookhong/Surfingkeys/blob/80929a374337120de09d61f384bee556fcb2da33/pages/default.js#L126-L128
nor 'f':
https://github.com/brookhong/Surfingkeys/blob/fa10d12b9a03dcdf9f6bdcc0860ffa8545f9552a/content_scripts/normal.js#L1068-L1075
set `tabbed` to `true`.

In the case of 'cf', this seems like it might be an oversight, given that we are actually opening the links in new tabs, so I would propose the following change:
https://github.com/brookhong/Surfingkeys/pull/1370
In the case of 'f', it's less clear what the correct behavior should be. Currently, it's using the `isElementClickable` logic:
https://github.com/brookhong/Surfingkeys/blob/4a274fe10edb5cae6787339171ec52323ef2eddb/content_scripts/utils.js#L51-L55
which doesn't always behave as I expect either, but I guess that should be expected given that they're implemented differently.

@brookhong 
What is the intended behavior for hints with `tabbed: true` vs hints with `tabbed: false`? They often generate different numbers of hints, but it's not always clear why.

**Comment by brookhong** [comment]
When `tabbed` is true, current implementation expects that there is `href` on an element for Surfingkeys to open it in new tab, please see https://github.com/brookhong/Surfingkeys/blob/master/content_scripts/hints.js#L592-L600. Theose clickable elements without `href` will not be included in hints with `tabbed: true`, since it may not make sense to open it in a new tab, for example, those page-inside javascript actions.

Yes, this kind of assumption is not accurate, since some elements without `href` do have a target URL, but I currently haven't had a good approach for that. Any suggestion that does work is welcomed.

**Comment by alexalekseyenko** [comment]
So it looks like one issue that can occur is with the `filterOverlapElements` function. When testing whether the result of `elementFromPoint`:
https://github.com/brookhong/Surfingkeys/blob/4a274fe10edb5cae6787339171ec52323ef2eddb/content_scripts/utils.js#L267
contains the element in question:
https://github.com/brookhong/Surfingkeys/blob/4a274fe10edb5cae6787339171ec52323ef2eddb/content_scripts/utils.js#L268
```js
el.contains(e)
```
can return `false` when `e` is tucked away inside shadow roots. For instance, 'f' will incorrectly filter out anchor links on [this page](https://www.rottentomatoes.com/search?search=dr%20strangelove).

We could do a recursive outward search like so:
```js
function isContainedWithin(inner, outer) {
  if (!inner) {
    return false;
  }
  if (outer.contains(inner)) {
    return true;
  }
  return isContainedWithin(inner.getRootNode().host, outer);
}
```
It doesn't seem to be much slower on that particular page, but I haven't done a proper analysis of the performance. What do you think?

**Comment by alexalekseyenko** [comment]
In case it's helpful, this is what I'm proposing:
https://github.com/brookhong/Surfingkeys/pull/1374

**Comment by vogler** [comment]
@brookhong How about also including those links without `href` in the hints, but clicking on them with ctrl/cmd pressed?
Of course this may lead to situations where the link is erroneously opened in the current tab. Maybe filter them by `cursor: pointer` to reduce the number of those cases. Or display those hints in a different color to indicate that they might open in the current tab.

Alternatively, one might try to cover some of the most common approaches like `onclick="location.href = ..."` and extract the URL to open in a new tab - Idk if that's already done.

**Comment by DavidGretzschel** [comment]
To clarify (and update) the issue:

The title should make the distinction between the two separate behaviours in the f-group and the cf-group (which includes cf, gf, af and C).

f-group:

![f-group](https://user-images.githubusercontent.com/23729465/146128564-a10400c4-0878-4071-8437-91f58bc95a4e.png)

cf, gf, af, C group:
![cf-group](https://user-images.githubusercontent.com/23729465/146128588-0f1cba78-1a20-4d21-9f87-b4e233768c1d.png)

This is a big issue for me.
It makes it really hard for me to intuitively use the more efficient vim-style navigation, since I can't predict what can be navigated to.
And I'm afraid, that the latter group being so pared down, forces me to use the mouse, anyway, since I can't replace ctrl-click apparently.
[I suppose, I could get around that with pressing yt to create a tab-copy and navigate to where I want from there, but it's convoluted and some sites don't load fast copies either.]

Afraid, I don't have the insight to solve the technical problem underlying it.
Just wanted to clarify the issue a little and emphasize, that it's very important to me.

**Comment by vogler** [comment]
@DavidGretzschel What is `af`?
Seems like the behavior changed since I opened the issue - can confirm `cf` is also missing hints.

**Comment by DavidGretzschel** [comment]
af is "open link in new active tab". You can press ? to see an overview of
all commands.

Am Mi., 15. Dez. 2021 um 16:33 Uhr schrieb Ralf Vogler <
***@***.***>:

**Comment by vogler** [comment]
Ah, I remapped `a` - I thought `?` would still show the composite mappings, but apparently it's smart about filtering unreachable strings.
~~~
map('a', 'E'); // af: link in active tab, ab: bookmark to selected folder
map('s', 'R'); // search selected with *, edit url, markdown, show last action...
~~~

**Comment by onguarde** [comment]
i actually prefer less hints on some websites. eg. google search. Reduced visual clutter and easier to press one letter instead of 2 letters to navigate to a link. 

cf, (open multiple links in background)
![image](https://user-images.githubusercontent.com/681355/155293391-fc4f789d-abf1-45b1-a063-e04ac1242daf.png)

f, (go to link in current tab)
![image](https://user-images.githubusercontent.com/681355/155293546-e83ca34c-ed71-4301-a588-b12d1ff850f1.png)

making this a customisable option may be a good idea, with sane defaults.

**Comment by b0o** [comment]
@onguarde You can create hints yourself using CSS selectors. Here's one I use for Google search results:

```js
// Using an array just to make the code more readable
const googleSearchResultSelector = [
  "a h3",
  "h3 a",
  "a[href^='/search']:not(.fl):not(#pnnext,#pnprev):not([role]):not(.hide-focus-ring)",
  "g-scrolling-carousel a",
  ".rc > div:nth-child(2) a",
  ".kno-rdesc a",
  ".kno-fv a",
  ".isv-r > a:first-child",
  ".dbsr > a:first-child",
  ".X5OiLe",
  ".WlydOe",
  ".fl",
].join(",")
api.mapkey("of", "Select Google result", () => api.Hints.create(googleSearchResultSelector), { domain: /google\.com/i })
```

![2022-02-23_01-54-50_region](https://user-images.githubusercontent.com/21299126/155296566-cb587bdb-6699-4e51-a00f-dc8cc20166da.png)


You can select more elements if you want, just inspect the Google results page and figure out the selectors you need. Unfortunately, Google's class names are a nightmare.

**Comment by onguarde** [comment]
@b0o that looks interesting, thanks for sharing. 
i'm just not so keen to maintain the nightmarish class names. With search cards in the result page, it will be quite complex to cover all bases.
