### ISSUE TITLE
"map a keystroke to another" doesn't actually map a keystroke to another

### ISSUE THREAD

**Issue by eyehol3** [brookhong/Surfingkeys#1313]
## Error details
SurfingKeys: 0.9.65

Browser: Brave 1.12.112 (Chromium: 84.0.4147.125) macOS 10.15.6

URL: twitter.com

## Context
so i have ukrainian layout besides the US. for some reason twitter hotkeys only work on US layout, i thought i would be able to remap ukrainian letters to latin letters via surfingkeys like this `map('ю','.', /twitter.com/i);` but it didn't work :)

**Comment by arizzubair** [comment]
Try with other destination key since '.' is already used to repeat previous action. 
Or, unmap or rempa '.' first and then try mapping.

**Comment by 097115** [comment]
I also can't map a key to emulate a system-wide hotkey?

Like, if I have a system-wide mapping <Ctrl-Alt-z>, and I want to map it to <Shift-d> in Surfingkeys so that by pressing <Shift-d> while in my browser my global hotkey <Ctrl-Alt-z> would get pressed -- I can't achieve that, right? Probably due to some security limitations?

@brookhong , Could you confirm this, please? :)

**Comment by brookhong** [comment]
@097115 Yes, that is impossible.
