### ISSUE TITLE
mapping a key for an extension?

### ISSUE THREAD

**Issue by zeltak** [brookhong/Surfingkeys#134]
Hi

i have been using an extension (atomic emacs..yeah some people actually use emacs :)) that opens input areas in emacs for editing. i can bind a key via the extension page in the bottom (the Keyboard shortcuts).
I was wondering if i can instead bind the key via SK to make it part of my SK insert mode workflow?

thx!

Z

**Comment by rosshadden** [comment]
[chromium-vim](https://github.com/1995eaton/chromium-vim) supports this by allowing users to register keys in the "Keyboard shortcuts" section of chrome://extensions/

This lets the extension work on pages it would otherwise not work on, which is very convenient to not break the immersion or consistency.

**Comment by brookhong** [comment]
The actions there in chrome://extensions/ for key binding are limited, which must be defined in `commands` section of file `manifest.json` first.

For now, only action `restartext` is defined there to restart Surfingkeys. Which actions do you guys need there?

And to talk with another extension is not doable without other extension's permission.
