### ISSUE TITLE
Can't read the clipboard in firefox 84

### ISSUE THREAD

**Issue by duguyipiao** [brookhong/Surfingkeys#1364]
## Error details

SurfingKeys: 0.9.68
Browser: firefox 84.0 in linux

## Context

In the latest stable version of firefox. The function `search selected with` does not work for the clipboard contents.
For example, if I press `sg`, it always searches the empty string in google when nothing is selected.
In the same computer, chrome works normally.

Related issue (maybe):
https://github.com/tridactyl/tridactyl/issues/3115

**Comment by duguyipiao** [comment]
According to https://github.com/tridactyl/tridactyl/issues/3115#issuecomment-748068195, this is probably because firefox disabled the old api `document.execCommand`.

**Comment by bovine3dom** [comment]
Unfortunately it's not quite as simple as copying what Tridactyl does because, IIRC, Google Chrome doesn't support the Clipboard API from background pages, but it does support it from content pages. Firefox only supports it on HTTPS content pages, so in Firefox it has to be used in the background for it to be useful.

I reckon it's probably just a Firefox bug, I don't think they would have meant to disable the `execCommand` API on purpose.
