### ISSUE TITLE
u should be mapped to scroll half-page up

### ISSUE THREAD

**Issue by neojski** [brookhong/Surfingkeys#141]
<kbd>?</kbd> is ok for help but <kbd>u</kbd> has better association with scroll half-page up (<kbd>ctrl-u</kbd> and <kbd>ctrl-i</kbd> in vim do that) which could be paired with <kbd>u</kbd> and <kbd>d</kbd> in surfingkeys.

I'd suggest changing this default.

**Comment by brookhong** [comment]
`e` is to pair with `d`, as it will help you to put only one hand(left) on keyboard to complete most actions. And it's near with `d`.

`u` is there for quick help.

**Comment by neojski** [comment]
That makes sense, though, I think <kbd>u</kbd> would better serve the same action as <kbd>d</kbd> rather than <kbd>?</kbd>. I don't see why <kbd>u</kbd> would mean `help` when in vim it means `undo` or `half-page up` (when used as <kbd>ctrl-u</kbd>).

**Comment by gabrielqv** [comment]
so can this be customized for each one's preferences?

**Comment by neojski** [comment]
This issue suggests changing the default.

**Comment by aspiers** [comment]
I agree that this default should be changed to scroll half a page up.  That's what I expected (from the behaviour of `less(1)`).

Also I've never seen another program use the `u` shortcut to display help, so for me the current default is very unintuitive and also unnecessary since it's already available via the much more intuitive `?` key.
