### ISSUE TITLE
Refused to execute inline script issue

### ISSUE THREAD

**Issue by whikwon** [brookhong/Surfingkeys#1416]
I made an issue before(#1411 ) because I couldn't copy the pdf url. Even after the url copy function is modified, the url copy still does not occur, and the following error occurs. 

Could you let me know why the error is occurring?

```
modules.min.js:5 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' https://www.google-analytics.com". Either the 'unsafe-inline' keyword, a hash ('sha256-Gcv5+R5RthyXrPWwTLIjv7xKg5n8vhIdMRP3Wy+kDj4='), or a nonce ('nonce-...') is required to enable inline execution.
```

**Comment by brookhong** [comment]
The error was cuased by https://github.com/brookhong/Surfingkeys/blob/master/content_scripts/clipboard.js#L46-L49, which is to handle some case when some sites disable document's copy API.

For me, URL copy works though the error happens, since the PDF viewer does not disable the document's copy API.
