### ISSUE TITLE
remap Alt-s disable command

### ISSUE THREAD

**Issue by duhd1993** [brookhong/Surfingkeys#1430]
## Prelude
* Could you find answer in below documents?

    1. [FAQ](https://github.com/brookhong/Surfingkeys/wiki/FAQ) / [常见问题](https://github.com/brookhong/Surfingkeys/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
    1. [README](https://github.com/brookhong/Surfingkeys/blob/master/README.md) / [读我](https://github.com/brookhong/Surfingkeys/blob/master/README_CN.md)
No
* Have you searched your problem in [issues](https://github.com/brookhong/Surfingkeys/issues)?
Yes. But there are too many. I may have missed some.
## Error details

SurfingKeys: 0.9.69

Browser: Mac OS X 11_2_3 Chrome/90.0.4413.0

URL: N.A.

## Context

There is no proper way to remap the shortcut for disabling/enabling surfingkeys. I'm able to bind a shortcut to disable surfingkeys. But itself is lost after disabling so I cannot re-enable. Alt-s is separately treated so it continues to work. Maybe a separate setting could be added just for this shortcut in addition to the main config file.
```javascript
mapkey('<Alt-k>','Disable surfingkeys', function(){
    Normal.toggleBlacklist();
})
```

**Comment by onguarde** [comment]
i'm trying to do the same. 
remap <alt-shift-s> to function "Toggle SurfingKeys on current site", (which is currently mapped to <alt-s>)

can't find any documentation on how to various mapkey function works ... 
really confusing 


following are what i've tried 

// not defined error
//map('<Ctrl-y>', '<alt-s>'); 
// unmap('<alt-s>');
// mapkey('<alt-y>', 'Toggle SurfingKeys on current site');

mapkey('<Ctrl-]>', 'Toggle SurfingKeys on current site', function () {
    RUNTIME("Toggle SurfingKeys on current site");
    RUNTIME("");
});

**Comment by onguarde** [comment]
personal_configures/Surfingkeys-config-ko.js at master · mindgitrwx/personal_configures
https://github.com/mindgitrwx/personal_configures/blob/master/Surfingkeys-config-ko.js

surfingkeys-conf/keys.js at master · b0o/surfingkeys-conf
https://github.com/b0o/surfingkeys-conf/blob/master/keys.js


referred to these example configs as well.

**Comment by onguarde** [comment]
latest try, map zoom key to +. still doesn't work 

```
unmap('zi');
mapkey('+', 'zi');
```

Reference,
Default mappings are not comprehensive · Issue #1325 · brookhong/Surfingkeys
https://github.com/brookhong/Surfingkeys/issues/1325

**Comment by onguarde** [comment]
Ended up using autohotkey to do the mapping, shame.

```
#If WinActive("ahk_class Chrome_WidgetWin_1") || WinActive("ahk_class MozillaWindowClass")

	; Surfingkeys extension - if <alt-shift-s> is pressed, send <alt-s>
	!+s:: Send !s

#IfWinActive 
```

**Comment by b0o** [comment]
The reason this isn't straightforward is that this specific keybinding needs special handling. 

Disabling Surfingkeys is technically possible with a user-defined keybinding (but requires using low-level `RUNTIME` calls). The problem is that once it is disabled, how would you re-enable it? Surfingkeys would be disabled, so your user-defined keybinding would not trigger. The only way to re-enable it for a site is to use the hard-coded `<Alt-s>` keybinding. Since there isn't a way to re-enable Surfingkeys for a site from the popup, only globally toggle, you would be locked out of Surfingkeys on that site if you couldn't use `<Alt-s>`.

I do agree that this keybinding should be configurable, though. A way to do it would be for a new option to be added to the extension-level keybindings (accessible in Firefox at `about:addons > Manage Extension Shortcuts > Surfingkeys`, or Chrome at `chrome://extensions/shortcuts > Surfingkeys`). These shortcuts are active even when SurfingKeys is disabled. This would make a good PR.

**Comment by brookhong** [comment]
Remapping special keybinding should be available now, please see https://github.com/brookhong/Surfingkeys/issues/1776.
