### ISSUE TITLE
Close tabs to the right/left 

### ISSUE THREAD

**Issue by tdtrung17693** [brookhong/Surfingkeys#147]
Hi. Is there any command for SurfingKeys to close tabs to the right/left ? I have read the README carefully, but didn't find any commands to do that.

**Comment by brookhong** [comment]
There are no such commands. But you could take advantage of [repeating actions by pressing number before mapkey](https://github.com/brookhong/Surfingkeys#repeats-action-by-pressing-number-before-mapkey).

For example, you have 5 tabs opened, and you're at the 3rd one, which means you have 2 tabs on your right, and 2 tabs on your left.

To close all the tabs on your left,

1. `r` to switch to the 4th tab
1. then `2x` to close 2 tabs.

To closes all the tabs on your right,

1. `g0` to jump the the 1st tab
1. `2x` to close 2 tabs.

**Comment by perfectayush** [comment]
@brookhong  Although what you propose is possible to do, it's not a convenient solution to the required problem. It's complicated to reason about as well. I am an ex cvim user and miss this feature a lot. So I have gone ahead and made changes to the extension, shamelessly copying skeleton code to do this from cvim. I earlier tried implementing this with js in SurfingKeys settings. But it's not possible to do this due to chrome security restrictions, which I guess is fair considering this feature.

PS: I was a pentadactyl user before switching to cvim and finally switching to SurfingKeys. Browsing experience in chrome is very pleasant with SurfingKeys. Thanks for your wonderful work
