### ISSUE TITLE
Error found in settings: ReferenceError: Hints is not defined

### ISSUE THREAD

**Issue by claimsecond** [brookhong/Surfingkeys#1578]
## Error details

I have next settings in my previous version's config:

```
// Hints settings
Hints.characters = "asdfghjkl";
settings.hintAlign = "left";
Hints.charactersUpper = false;
```
After update to SurfingKeys: 1.0.0 I got "Error found in settings: ReferenceError: Hints is not defined"

SurfingKeys: 1.0.0

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36

URL: All the sites.

## Context

**Please replace this with a description of how you were using SurfingKeys.**

**Comment by fanlushuai** [comment]
https://github.com/brookhong/Surfingkeys/wiki/Migrate-your-settings-from-0.9.74-to-1.0
 sovle the reffrencError , but not works correctlly.

test below：

```
api.Hints.characters='abcd';  // Type `f` ,it still show build-in chars
```

**Comment by aspiers** [comment]
I suggest that a rethink of the update process is needed.  Realistically, the vast majority users are not going to check release notes for each upgrade - in fact, they won't even *know* that an upgrade happened, because the browser does it automatically.  So the chances of us finding https://github.com/brookhong/Surfingkeys/wiki/Migrate-your-settings-from-0.9.74-to-1.0 without being automatically pointed at it are extremely low.  That results in most users being caught off-guard by this error, so it is not surprising that there are already multiple duplicate reports of issues relating to this backward-incompatible upgrade (#1576, #1580, and #1574 for a different issue).

## Suggested solutions

1. Avoid backwards-incompatible changes where possible.
2. Automate the migration of settings from old format to new format.
3. If 2. is not possible, then gracefully handle those cases with helpful errors which point the user to the migration page, to avoid them having to google for the solution.

Additionally, I suggest making sure that all popup errors from SurfingKeys are clearly labelled as SurfingKeys errors, otherwise it is not at all obvious whether these errors are coming from a browser extension, the browser itself, or the page being visited - and this makes it much harder to figure out the solution.

**Comment by claimsecond** [comment]
Thank you. That worked on this issue. But then I got other error messages... Looks like I have to rewrite now all the scripts I have... :(

**Comment by krmbzds** [comment]
I use `f` as a toggle (like in https://github.com/brookhong/Surfingkeys/issues/733).

Refactored my settings but still get default characters.

Do not remove this from the public API please. :pray:

**Comment by aspiers** [comment]
[**@fanlushuai**](https://github.com/fanlushuai) commented on [December 29, 2021 9:05 AM](https://github.com/brookhong/Surfingkeys/issues/1578#issuecomment-1002471056 "2021-12-29T09:05:02Z - Replied by Github Reply Comments"):
> [https://github.com/brookhong/Surfingkeys/wiki/Migrate-your-settings-from-0.9.74-to-1.0](https://github.com/brookhong/Surfingkeys/wiki/Migrate-your-settings-from-0.9.74-to-1.0)  
> sovle the reffrencError , but not works correctlly.
> 
> test below：
> 
> ```
> api.Hints.characters='abcd';  // Type `f` ,it still show build-in chars
> ```

This doesn't work for me either, and https://github.com/brookhong/Surfingkeys/blob/master/docs/API.md doesn't list `characters` as part of the API.  So this seems to be a regression from 0.9.74.

**Comment by i-zanis** [comment]
I followed the instructions. I still see the same error. I haven't changed anything else but remove the F from the hints.

**Comment by brookhong** [comment]
Since 1.0.2

* `Hints.numericHints = true;` was replaced with `Hints.setNumeric()`.
* `Hints.characters = "abcd";` was replaced with `Hints.setCharacters("abcd")`.

**Comment by aspiers** [comment]
`Hints.setCharacters` did not work for me, however `api.Hints.setCharacters` did.  Please can you update the docs to reflect this?

**Comment by Stvad** [comment]
Can you please document this api change in the migration guide?

**Comment by krmbzds** [comment]
It seems like it is documented both in migration and API docs:
- https://github.com/brookhong/Surfingkeys/wiki/Migrate-your-settings-from-0.9.74-to-1.0
- https://github.com/brookhong/Surfingkeys/blob/master/docs/API.md#hintssetcharacters

You need to prefix listed methods in the migration guide with `api`. It is explained in the first paragraph of the migration guide. Breaking changes are listed too.

If you use the following snippet to make it compatible with your old scripts then you don't have to prefix methods with `api`, but you still have to refactor breaking changes (i.e. if you have `addSearchAliasX`, `numericHints`, `characters`, or `blacklistPattern` in your config).

```
const {
    aceVimMap,
    mapkey,
    imap,
    imapkey,
    getClickableElements,
    vmapkey,
    map,
    unmap,
    cmap,
    addSearchAlias,
    removeSearchAlias,
    tabOpenLink,
    readText,
    Clipboard,
    Front,
    Hints,
    Visual,
    RUNTIME
} = api;
```

**Comment by aspiers** [comment]
[**@krmbzds**](https://github.com/krmbzds) commented on [December 31, 2021 4:38 PM](https://github.com/brookhong/Surfingkeys/issues/1578#issuecomment-1003414678 "2021-12-31T16:38:19Z - Replied by Github Reply Comments"):
> It seems like it is documented both in migration and API docs:
> 
> *   [brookhong/Surfingkeys/wiki/Migrate-your-settings-from-0.9.74-to-1.0](https://github.com/brookhong/Surfingkeys/wiki/Migrate-your-settings-from-0.9.74-to-1.0)
> *   [`master`/docs/API.md#hintssetcharacters](https://github.com/brookhong/Surfingkeys/blob/master/docs/API.md#hintssetcharacters)
> 
> You need to prefix listed methods in the migration guide with `api`.

Yes, I know, [as mentioned above](https://github.com/brookhong/Surfingkeys/issues/1578#issuecomment-1003406731). 

> It is explained in the first paragraph of the migration guide. Breaking changes are listed too.

As [previously explained](https://github.com/brookhong/Surfingkeys/issues/1578#issuecomment-1002546857), documenting the `api` prefix requirement and other breaking changes in the migration guide is not nearly sufficient to avoid quite a lot of confusion from power users.  But @brookhong has already [graciously received and responded to this feedback](https://github.com/brookhong/Surfingkeys/issues/1542#issuecomment-1002824960).
