### ISSUE TITLE
Surfingkeys not recognizing keyboard layout

### ISSUE THREAD

**Issue by benutzer193** [brookhong/Surfingkeys#16]
I have a qwertz keyboard with special characters like ö,ü,ä. Some symbols are not recognized correctly, e.g. if I want to press **'** I actually have to press **ä** on my keyboard.

On the other hand **y** and **z** are recognized.

I hope I could make the problem clear.

**Comment by AlexIvasi** [comment]
Confirm that bug. 
I'm using Standard En QWERTY keyboard and experiencing keyboard layout issues as well.
e.g. pressing Ctrl + Num Pad 9 - shows SurgingKeys help dialog instead of switching to the latest tab in session.
creating Num Pad 8 - Vim Mark - stores it with  ä character, though it is still working when you press  '  + Num Pad 8


p.s. By the way Brook - I can see that Chrome's store / Questions sections is turned off now and is redirected to github - where is the best place to ask questions? (if it is possible)
Thanks Brook!

**Comment by brookhong** [comment]
I got below mappings from testing.

    íöüóőúűéá-
    `0-=[]\;'/

So I guess the ideal solution for users with qwertz keyboard is to customize your settings like below

    mapkey("á", 'Jump to vim-like mark', Normal.jumpVIMark, 1);

**Comment by benutzer193** [comment]
The mappin you provided is not working for me. I found the following mapping by chance:

    mapkey("?", 'Jump to vim-like mark', Normal.jumpVIMark, 1);

Now it's possible for me to check every other button, because if I press

    ' + *any button*

it shows:

    No mark '*any button (keyname recognized by Surfingkeys)*' defined.

The problem with this solution is, although I can make my preferred mapping, Surfingkey prints out the wrong keynames.

Do you have any idea for a solution, that the keynames are recognized correctly and independent of the layout?

**Comment by brookhong** [comment]
I tested with Hungarian(qwertz layout).
![hungarian](https://cloud.githubusercontent.com/assets/288207/12171422/b8003f1e-b584-11e5-8552-3898acd4a138.png)

Could you please let me know your language and keyboard layout? It would be helpful if you can attach a  picture of your keyboard.

**Comment by benutzer193** [comment]
It's a German QWERTZ keyboard:

![Schenker M504 keyboard](http://www.notebookcheck.net/fileadmin/Notebooks/Schenker/M504/keyboard1.jpg)

**Comment by brookhong** [comment]
Please use work-around from @nightscape(thank his idea) to create your own mappings.
1. press `Ctrl-1`, then press the key you'd like to use to see what Surfingkeys gets from it.
2. use `map` to replace the default key.
