### ISSUE TITLE
Surfingkeys extension causes black blocks when generating pdf files with jsPDf .html() method 

### ISSUE THREAD

**Issue by wildhart** [brookhong/Surfingkeys#1672]
When this extension is installed alongside https://npmjs.com/package/pdfjs, and the jsPDF `doc.html(...)` method is used to generate a PDF from html content, the pdf output has black blocks in the content:

![image](https://user-images.githubusercontent.com/12505024/155005897-3e1799e4-6ddb-4f87-8c3e-438e97862f37.png)

```
import { jsPDF } from "jspdf"; // for generating pdf from html

(window as any).btnclick = () => {
  const doc = new jsPDF("p", "pt", "a4", true);
  const html = `Hello <b>There!</b> everyone2!`;
  doc.html(html, {
    margin: 20,
    callback: (doc) => {
      doc.save("hello.pdf");
    }
  });
};
```

I have a repro here: https://codesandbox.io/s/surfingkeys-breaks-jspdf-dzkhfd?file=/index.html

Through some painful troubleshooting I've narrowed this down to having the SurfingKeys extension installed and enabled.  I've tried this in a fresh chrome profile.

Somehow I think this extension is adding some css to the `html` and `body` elements on the page.

**Comment by b0o** [comment]
I spent a while trying to debug this using your repro, but it's rather difficult because jsPDF doesn't seem to offer any good introspection or debugging APIs. I would like to see the full HTML of the document just before it's converted into a PDF, but that doesn't seem easily doable unless I'm missing something. If you spend some time stepping through the jsPDF code in the devtools debugger, you should be able to set a breakpoint just before the HTML->PDF rendering and inspect the value of the variable that holds the HTML. If you were able to find it and post it here, it would help to figure out what's going on.

Another option, if this issue is local to your or your organization's machines, you could use an enterprise policy to fully disable SurfingKeys on your PDF generator site:

- [Prevent Chrome extensions from altering webpages - Chrome Enterprise and Education Help](https://support.google.com/chrome/a/answer/9031935?hl=en)
- [Allow or block apps and extensions - Chrome Enterprise and Education Help](https://support.google.com/chrome/a/answer/6177431?hl=en)

**Comment by wildhart** [comment]
Thanks for looking into this.

Internally jsPDF uses htm2canvas, and I've been able to make a smaller repro with just html2canvas:

https://codesandbox.io/s/surfingkeys-breaks-html2canvas-kedcgi?file=/index.ts

The first render works fine, but pressing the button a second time gives this:

![image](https://user-images.githubusercontent.com/12505024/155191570-78ad05d6-3a66-4fdd-a66e-5d513489953c.png)

Inspecting the body shows this element:

![image](https://user-images.githubusercontent.com/12505024/155191664-a061baa4-300e-4f0d-a90b-8e0c0537ed0e.png)

Deleting that element and pressing the button again works fine.

When I have sometime maybe I'll step through the code...

**Comment by b0o** [comment]
I was able to "fix" it in your second codesandbox example, but the same trick doesn't work in the original codesandbox:

https://codesandbox.io/s/surfingkeys-breaks-html2canvas-forked-i4668i?file=/index.ts

**Comment by wildhart** [comment]
@b0o Thanks very much for looking into this.  Unfortunately I don't have much time to investigate any further at the moment.

I also think this is unlikely to be a problem for my client who are unlikely to have SurfingKeys installed like us geeks ;-)

Feel free to close this issue if you want.  Thanks for your SK, btw - I love the extension!

**Comment by brookhong** [comment]
Thanks @b0o for looking into this, I have committed a fix for this, which basically inserts the hints host element on demand rather than initially. @wildhart please verify whether it works for your case.

**Comment by wildhart** [comment]
Yes @brookhong , this fixes the problem when generating PDFs on my site, thank you for your clever solution!
