### ISSUE TITLE
Exchange messages with programs other than Firefox?

### ISSUE THREAD

**Issue by stevenbarragan** [brookhong/Surfingkeys#1713]
First of all thanks for making my life easier with this plugin.

I'm just curious about this permission required in Firefox "Exchange messages with programs other than Firefox" and why is it needed?

**Comment by brookhong** [comment]
I think that message comes with the permission request for `nativeMessaging`, which is for nvim integration. Please see more at https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_messaging

But this permission currently is not necessary for Firefox since nvim integration is not ready for the browser.

**Comment by vonHabsi** [comment]
After the permission is granted can it be disabled in the Settings if it is not needed?

**Comment by brookhong** [comment]
No, permission is controlled by browser itself rather than Surfingkeys.

Please note that if you don't set up the local json file, Surfingkeys can not exchange anything with local program even the permission is granted.
