### ISSUE TITLE
ctrl-p and ctrl-n to scroll up and down

### ISSUE THREAD

**Issue by grolongo** [brookhong/Surfingkeys#1935]
Hello, I'm trying to rebind `ctrl-p` and `ctrl-n` to scroll up and down (Emacs style), on Firefox.  

In the surfkeys settings I'm using:
```javascript
api.map('<ctrl-p>', 'k');
api.map('<ctrl-n>', 'j');
```  
Unfortunately that doesn't work.  
After saving the new settings and testing `ctrl-n` still opens a new window and `ctrl-p` opens the print pop-up.  

Is it not possible to overwrite default Firefox bindings? Or am I doing something wrong?

**Comment by daidaiworm** [comment]
not working here.

Surfingkeys 1.12
win10 22H2 19045.2546
Chrome 109.0.5414.120
Edge 109.0.1518.70

**Comment by brookhong** [comment]
It's `Ctrl` instead of `ctrl`, so it should be(which should work under Mac)

    api.map('<Ctrl-p>', 'k');
    api.map('<Ctrl-n>', 'j');

Regarding `ctrl-n` to open a new window and `ctrl-p` to open print popup(under Windows and Linux), those shortcuts are from browser itself, which can not be modified through Surfingkeys.

The only way to change those is to make code change in Browser itself, please see https://brookhong.github.io/2021/04/18/brook-build-of-chromium.html
