### ISSUE TITLE
is support sub-directory?

### ISSUE THREAD

**Issue by SugeunOh** [brookhong/Surfingkeys#197]
first at all, thank you so much. I love surfingkeys !!

(I also tried blacklist, but it's using window.location.origin.)
I want to make blacklistPattern like below:

http://my.test.com/jira  - use default key
http://my.test.com/mail  - use default key
http://my.test.com/wiki - use surfingKeys.
http://my.test.com/test - use surfingKeys.

so I tried.. but it's not working. is it weird or am I wrong?
settings.blacklistPattern = /my.test.com\/jira|my.test.com\/mail/i;

(I also tested in node repr : )
> a = /my.test.com\/jira|my.test.com\/mail/i;
/my.test.com\/jira|my.test.com\/mail/i
> a.test('my.test.com/jira')
true
> a.test('my.test.com/jira/others')
true
> a.test('my.test.com/mail/others')
true
> a.test('my.test.com/wiki')
false

**Comment by axs221** [comment]
From what I see, the settings attempted should be correct. But the code isn't passing the blacklistPattern through correctly.

content_scripts/content_scripts.js : checkBlacklist(sb)

The "sb" settings object here has a key for "blacklistPattern", but it appears to be an empty object, not a regex. Since it has no test() method, it short circuits and never performs the regex comparison.

I would have to dig in further into why "blacklistPattern" isn't being parsed as a regular expression.

**Comment by brookhong** [comment]
Thanks guys.

It is a bug, fixed in 0.7.1.
