### ISSUE TITLE
Can't type a newline after a colon without inserting an emoji

### ISSUE THREAD

**Issue by 0xR** [brookhong/Surfingkeys#282]
Steps to reproduce:
1. Start in an input field like a textarea
1. Type a colon (":")
1. Hit the enter key
1. Notice that the colon is now a "grinning face" emoji

Possible solutions
1. To be honest I use surfing keys for its hot keys. I don't need it to insert emojis for me. I think it could be a different chrome plugin for emoji
1. Don't automatically select the first emoji, but the <tab> key to select an emoji.

As a workaround I wonder how to disable the emoji functionality alltogether.

**Comment by brookhong** [comment]
Add below in your settings to disable it:

    iunmap(":");

**Comment by maximbaz** [comment]
@brookhong what do you think about making emoji popup appearing not immediately after typing `:`, but after typing at minimum two characters after the `:`? This is how Slack has implemented this, I think it makes sense, it will make this feature less obtrusive, and yet will help a lot with entering emojis!

**Comment by brookhong** [comment]
@maximbaz 

Nice suggestion except the part of `Enter`/`space` to cancel.

If `Enter` is to cancel, then which key would be used to confirm an emoji from suggestion list?

And for `Space`, they are in the text annotation of some emoji-s.

**Comment by maximbaz** [comment]
Agree, that was not a good idea. I was just thinking how to make "an early exit", how to understand from the start that a user is not intending to enter emojis. 

How about this adjustment: if <kbd>Enter</kbd> or <kbd>Space</kbd> are pressed _as one of the two characters_ that we are waiting to see before opening the popup, that means user doesn't want to enter emojis and so the popup should not appear at all.

Examples:

> These are numbers: one, two, three.

In this example when I entered <kbd>:</kbd>, the plugin began to await for the two characters before showing the emoji popup. The next two entered characters were <kbd>Space</kbd><kbd>o</kbd>, and since one of them is <kbd>Space</kbd>, the plugin should understand that I'm not going to enter emojis,  I'm entering a list, and thus should not present the popup.

> Some text :D more text

In this example it is very similar, after I entered <kbd>:</kbd>, the next two entered characters were <kbd>D</kbd><kbd>Space</kbd>, and even though <kbd>Space</kbd> is in a text-annotation for some emojis, it is very unlikely that somebody is searching for an emoji `END arrow` or `ID button` by entering one letter and then a <kbd>Space</kbd> (like it happens now). More likely they aren't going to enter emojis at this point at all.

> These are three numbers:
> = one
> = two
> = three

This example is again similar, after I entered <kbd>:</kbd>, the next two entered characters were <kbd>Enter</kbd><kbd>=</kbd>, and since <kbd>Enter</kbd> was one of them, it means I'm entering a multi-line list, so I don't want to see emojis popup at this point.
