### ISSUE TITLE
Sync settings

### ISSUE THREAD

**Issue by xcv58** [brookhong/Surfingkeys#3]
I have multiple machines, and manage settings over them is tedious.

Even someone doesn't have multiple machines. But they may have different profiles for chrome.

So sync settings is an useful feature.

One possible way is using `chrome.storage.sync` /https://developer.chrome.com/extensions/storage#property-sync

It has `102,400 bytes QUOTA_BYTES = 100 KB` quota. I think it's reasonable size for this extension.

Even if it's not large enough. We can still build a sync service based on it and third party service like: http://myjson.com/

**Comment by brookhong** [comment]
Thanks for the very constructive comments.

Yes, `chrome.storage.sync` will be an option. Meanwhile I'm thinking about loading settings from local file system, so that users can manage their own `surfingkeys.js` in whatever sync service they like, dropbox, github, bitbucket...

Of course, a mapping key will be provided for user to load from local file system quickly.

**Comment by xcv58** [comment]
The good part of chrome.storage.sync is that it can provides seamless sync experience, i.e. just login Google account and all settings coming as extension sync.

I think it's still possible to produce similar seamless sync feature with third party services. For example, we can use chrome.storage.sync to store and sync gist url or a dropbox public link.
