### ISSUE TITLE
Inserting emoji doesn't work on Facebook/Whatsapp Web

### ISSUE THREAD

**Issue by mselee** [brookhong/Surfingkeys#327]
### Steps to reproduce

1. Type ':gri' to show the emoji popup
2. Select any emoji and press Enter
3. Press Enter to send this emoji

### Bug
It sends ':gri' instead of the actual emoji

### Workaround
After selecting an emoji and pressing Enter, press Space. Now if you press Enter to send, it will be properly sent as an emoji.

**Comment by maximbaz** [comment]
I saw this elsewhere as well. This behavior is likely because Facebook is listening on `change` event to update the internal memory of what is entered in the box. The fix for inputs and textareas is simple, `$(elm).change()` will do the trick. However, for contenteditable divs (which is what Facebook happens to use) I'm not sure on which exactly element to fire this `change` event.
