### ISSUE TITLE
Is there official Vivaldi support?

### ISSUE THREAD

**Issue by MaikoID** [brookhong/Surfingkeys#332]
Hey guys, nice work, very very nice work. I'm used to pentactyl and vimperator, both from Firefox, and this extension is great, even better than these. I'm using Vivaldi the chrome based browser now and I'm also impressed and would like to ask if there is support for it.

It appears that is not 100%, more than 90% I guess, however, there are some issues:

1. github text area for example I can't press ENTER without closing the vim editor (SHIFT->ENTER works).
1. inconsistent behavior at Google Inbox (something doesn't work, like the ?, (I disabled the Google Inbox's shortcuts) and Quora the hints doesn't seems to discover some links.
1. the new tab shortcut (su) looses focus after the enter, however he browser has focus and its internal shortcuts, eg: ctrl+tab, works. So only the Sufingkeys stops to respond.

BR =)

**Comment by brookhong** [comment]
1. can not reproduce on my laptop, I can close the vim editor by pressing enter.
2. can not reproduce too for google inbox. And for quora, that's possible, could you please upload some screenshots here?
3. Reproduced, but this looks like an issue from Vivaldi. I had reported this to Vivaldi team, unfortunately they did not provide an URL to track back. Otherwise, I'll put it here.

**Comment by MaikoID** [comment]
Hi, thanks for your response.

I had some issues with Vivaldi and I stopped using it, in my opinion it's not ready enough for daily usage yet. So its more difficult to me reproduce the reported problems now and I'm back to Chrome.

But from all 3 problems I asked about the last one was the most important and you solved it by me you can close this thread now.

Thanks.

**Comment by intre4si32** [comment]
I use Surfingkeys successfully on Vivaldi.
