### ISSUE TITLE
[Suggestion] Place the current at the end of text when go to edit box

### ISSUE THREAD

**Issue by laphylee** [brookhong/Surfingkeys#410]
The cursor will be at the beginning currently. I think most of case user want to put the cursor at the end of text, which is convenient to append/edit the text.

**Comment by brookhong** [comment]
The cursor is not positioned deliberately at beginning of text, cursor is there just because that it was there before focus was removed from the edit box.

If you leave the cursor in middle of the text, and escape the edit box. Then use `i` to enter the edit box again, you'll find that the cursor is still in middle of the text.

**Comment by laphylee** [comment]
Thanks for your explanation!
You are right. But if it's a search box, you input some text (cursor at the `end`) and click button, then you jump to the search box, the cursor will be at the `beginning` of the edit box again.

**Comment by rosshadden** [comment]
@laphylee I made `a` do what you are asking about.  https://github.com/rosshadden/dotfiles/blob/master/src/.config/surfingkeys/config.js#L99-L111

**Comment by brookhong** [comment]
New setting `settings.cursorAtEndOfInput` added for this.
