### ISSUE TITLE
Could mapkey() support multi-char argument in action_code

### ISSUE THREAD

**Issue by laphylee** [brookhong/Surfingkeys#413]
mapkey() is very powerful. I have a scenario like following: I made a plugin to show numbers on each tab. For 1~~9 tabs, I could use build-in Ctrl-1~9. For 10+ tabs, I'd like to map it to keys like "t10", "t11", etc. 
Could mapkey() support multi-char argument in action_code? Or do you have better suggestions? 
Thanks a lot!

**Comment by brookhong** [comment]
No, `mapkey` does not accept argument of multiple chars.

The problem here is that we have no way to determine whether an action should be triggered when first char of the argument was input. For example, when you need `t11`, you input `t1` then `1`, the action for `t1` will be triggered right away.

One possible solution is that we could wait for some time(such as 500 milliseconds) for next `1`. But this will have large impact on those mappings with argument only one char, such as `t8` / `t5`.

For me, the most intuitive way is to jump to the last tab with `g$`, then several `E` to locate the target tab.

If there are too many tabs, `T` may be a better option.

**Comment by laphylee** [comment]
Thanks brookhong! I understand your concern.
In cvim, key `<N>%` will go the Nth tab. In Surfingkeys, the prefix number is used to repeat action N times. Could the prefix number support two modes: repeat or pass it as parameter?

**Comment by brookhong** [comment]
Nice.

Since 0.9.0, you could use `11T` to jump to the 11th tab, but this is specially for `Front.chooseTab()`.
