### ISSUE TITLE
Vim Like Marks with Multiple Keys

### ISSUE THREAD

**Issue by rwinch** [brookhong/Surfingkeys#431]
I'd love for Surfkeys to support [Vim Like Marks](https://github.com/brookhong/Surfingkeys#vim-like-marks) with multiple keys. For example, I manage a lot of GitHub projects and I'd like `` `ghsk`` and then `Enter` to be able to take me to **G**it**H**ub **S**urf**k**eys

Could support for this be added? If not, is there an easy way to use the extensions to support managing the marks and navigating to them?

Thanks for such an awesome plugin!

**Comment by brookhong** [comment]
You could easily achieve that by adding something like below in your settings:

    mapkey(';ghsk', 'Open Surfingkeys on github', 'tabOpenLink("https://github.com/brookhong/Surfingkeys")');


Vim-like marks is quick marks, which won't work with multiple keys.

**Comment by cPMarco** [comment]
I'm not going to open a new feature request: the [backtick mark](https://vimhelp.org/motion.txt.html#mark-motions) functionality, because of the comment:

> Vim-like marks is quick marks

I guess that means the backtick isn't possible.  I only want the backtick for extreme convenience and cross-usage of Surfingkeys to vim, since I use `mm` as my most common mark in vim.  backtick-m is much easier to type than single-quote-m.
