### ISSUE TITLE
Scroll Does Not Work Anyway

### ISSUE THREAD

**Issue by OscarGong** [brookhong/Surfingkeys#432]
The scroll related functions does not work anyway, like ' j', 'k', 'd', 'e'.

But others functions work fine.

Even after restore to default mapping.

**Comment by brookhong** [comment]
Could you please provide the URL that you're having this issue?

And you could also try `cs` to change scroll target first.

**Comment by OscarGong** [comment]
In my part, not a specific URL, every URL have this glitch.

No, it isn't the scroll target cause this. So it's extremely weird.

Any workflow could help me check out where the problem is?

**Comment by cbrwizard** [comment]
Hey, I am using this plugin regularly and just today (maybe a couple days ago, didn't browse much) the navigation stopped working for me too. For instance, I can't scroll on this page. I didn't switch any settings. Might be related to Chrome update? Can I see debug messages somehow?

**Comment by OscarGong** [comment]
Yes, same as @cbrwizard. I literally did not change any settings. Just one day, boom, I can't scroll!

I am using Chrome beta. Later I will try Stable and Canary.

**Comment by OscarGong** [comment]
I think I got where the question is.  It only happens on Chrome beta (v61) and Chrome Canary ( v62).

Is google disable some API on new version?

**Comment by lervag** [comment]
This also happens to me. I'm on Chrome beta, 61.0.3163.31, on Arch Linux.

**Comment by cbrwizard** [comment]
Switching back to stable Chrome made the scrolling work again. I hope Surfingkeys gets working again before next Chrome's version release!

**Comment by rosshadden** [comment]
Happens to me in Chrome 61 on Arch Linux as well.

**Comment by rosshadden** [comment]
Just had a strange discovery.  I found [a page](https://smash.gg/tournament/shine-2017/events/melee-singles/brackets) on which all of these work.  So I guess in some way it depends on the page.

I generally try at least `gg` and `G` on every page I hit, whereas I have `hjkl` and other stuff still being controlled by [mouseless](https://github.com/hbt/mouseless) until they work with surfingkeys.  I left `gg` and `G` unmapped so that I could see when it gets fixed, and was suprised to find it work on one site but not others.

**Comment by perpen** [comment]
Same on chromebook, Chrome 61

**Comment by BlackCapCoder** [comment]
I also have this issue in Chromium 62.0.3192.0 on Arch Linux

**Comment by brookhong** [comment]
Thanks guys.

I reproduced this issue with Chrome 61.
Fixed in 0.9.6.
