### ISSUE TITLE
Question: Modular es2015+

### ISSUE THREAD

**Issue by simonwjackson** [brookhong/Surfingkeys#534]
@brookhong How do you feel about *slowly* moving towards modular isolated JavaScript components (`import & export`)?

I've noticed there are several functions & variables in the global namespace. Moving towards more isolated components could reduce potential undesired naming collisions.

Isolating It could also help simplify testing, which is also something I would like to introduce to the project in the future.

Let me know if you have any thoughts on this.

**Comment by brookhong** [comment]
I had thought about this for memory usage reduction and performance improvement. But I haven't figured out an ideal way to make it.

Here are some of my concerns.

* I want to keep current code able to be loaded as an unpacked extension directly, so that I could always use it without building.
* I don't like duplicate code in distribution, I like it small.

**Comment by simonwjackson** [comment]
@brookhong I understand not wanting duplicate code in distribution.

It looks like Chrome natively supports [ES6 modules](https://medium.com/dev-channel/es6-modules-in-chrome-canary-m60-ba588dfb8ab7), but i have no idea how to impliment them into a chrome extension 😄
