### ISSUE TITLE
Surfingkeys is preventing websites from loading

### ISSUE THREAD

**Issue by ClassicOldSong** [brookhong/Surfingkeys#675]
## Error details

SurfingKeys: 0.9.26

Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36

URL: https://www.jd.com/

## Context

Websites like JD recently never finishes loading with SurfingKeys enabled. GitHub suffers the same problem but at least it could load after some attempts to reload while JD never finishes loading and only displays a header. I could not address the problem because the Chrome develop tool shows nothing wrong. Hope you can have an investigation into this issue, thanks!

**Comment by brookhong** [comment]
I could not reproduce this issue, could you try to re-install Surfingkeys?

**Comment by ClassicOldSong** [comment]
Re-installing doesn't help. Even a brand new installation of Chrome on a brand new PC with this plugin enabled has this issue. Currently disabled this plugin.

**Comment by brookhong** [comment]
Sorry about that, I could not reproduce it.

Let's see if there is anyone else seeing same issue that could provide more error info.
![jd](https://user-images.githubusercontent.com/288207/38164416-f85f7ba4-3536-11e8-8720-cb0242ec92c0.gif)

**Comment by ClassicOldSong** [comment]
@brookhong Click into an item and see if the price could display correctly

**Comment by brookhong** [comment]
SurfingKeys: 0.9.28

Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3329.0 Safari/537.36

Everything works well on my side.
![image](https://user-images.githubusercontent.com/288207/38180816-c4956da2-3661-11e8-875d-a9e84f010cac.png)

**Comment by ClassicOldSong** [comment]
![2018-04-02 11 46 00](https://user-images.githubusercontent.com/10512422/38182413-d506d37e-366b-11e8-9460-f06016e08014.gif)
Still bolcking page load...

**Comment by alswl** [comment]
In my case, it block zhihu.com loading.

Google Chrome: Version 69.0.3486.0 (Official Build) dev (64-bit)

**Comment by veryeasily** [comment]
This is still broken for me, most noticeably on GitHub (seems the same as #770 ). I'm on Ubuntu 16.04 with Chrome `Version 69.0.3472.3 (Official Build) dev (64-bit)`. The largest issue is that simply disabling the extension on that domain does not fix the issue. The extension needs to be completely turned off. Is there any other information I could provide that would help?

**Comment by lgjmac** [comment]
brook thanks a lot for your reply to my email a while ago.. sorry i didn't i should have done so. 
this is an issue; reproduce using canary or (developer) 64bit. after the new look change
particularly bad in developer 64bit at the moment

my config:
map("c", "S");
map("C","D");
Hints.characters = "ajskdlghewioruvncm";
settings.scrollStepSize = 300;
settings.smoothScroll = true;
settings.hintAlign = "left";
settings.hintsThreshold = 200;
settings.showModeStatus = true;
settings.omnibarSuggestion = true;
settings.omnibarMaxResults = 8;
Hints.style('border: solid 3px #3a5f82; color:#fff; background: initial; background-color: #3a5f82; font-size: 16pt;');

however, very latest canary is working okay... 
it may be a google bug ;;; quite a change in design
i suggest wait and see rather than panic
