### ISSUE TITLE
change keymap in pdf viewer

### ISSUE THREAD

**Issue by PPanter92** [brookhong/Surfingkeys#716]
I change my scrollkeys to ijkl in normal, visual and insert mode, and for ace editor as well but when I open a PDF via the included js viewer it uses the default keymap. Is it possible to change the 'pdf keymap' somehow?

**Comment by brookhong** [comment]
This is because that `unsafe-eval` was removed from `content_security_policy` in manifest.json.

And for security reason, there is no possibility to bring it back.

**Comment by vogler** [comment]
Could you explain the problem? What's the difference in loading settings between the internal PDF viewer and another website?
I assume it could be fixed by adding `unsafe-eval` again which you want to avoid?
Is it a pdf.js issue that maybe has been fixed? https://github.com/mozilla/pdf.js/issues/10387

**Comment by brookhong** [comment]
The pdf viewer has its URL as chrome-extension://gfbliohnnapiefjpjlpjnehglfpaknnc/pages/pdf_viewer.html, which is a built-in page from SurfingKeys, and its content security policy is specified in `manifest.json`, which does not allow `unsafe-eval`.

But to load custom user script need `unsafe-eval` on built-in pages, please see https://github.com/brookhong/Surfingkeys/blob/master/content_scripts/content_scripts.js#L302

Yes, adding `unsafe-eval` back again could solve the issue, but [Add-ons for Firefox (en-US)](https://addons.mozilla.org/en-US/firefox/) won't accpet that. Please see https://github.com/brookhong/Surfingkeys/blob/master/pages/changelog.md#0919

**Comment by vogler** [comment]
My main issue with the default pdf keymap is https://github.com/brookhong/Surfingkeys/issues/1226

Instead of using full-blown `eval` could we do a mini-interpreter that maybe only filters out simple `map(x, y)` statements (which are easy to parse) and executes them? That should avoid the need for `unsafe-eval` and still support simple remappings in the pdf viewer.
