### ISSUE TITLE
Error message: "Error found in settings: ReferenceError: $ is not defined"

### ISSUE THREAD

**Issue by laphylee** [brookhong/Surfingkeys#734]
It show `Error found in settings: ReferenceError: $ is not defined` error message from today. 

I used jquery in the config file, such as:
`mapkey(';r', 'Remove Dida reminder popups', function(){$('#reminders-modal').remove(); }, {domain: /dida365\.com/i});`

I saw you have a new commit saying that "removing jquery". Does it mean it doesn't support using jquery in the config file now? Is there any workaround that I could still use jquery since I have plenty of jquery code in the config file? 

Thanks a lot!

**Comment by brookhong** [comment]
Yes, as it is stated here.
https://github.com/brookhong/Surfingkeys/blob/master/pages/changelog.md#0930

Sorry, there is no workaround so far, it is not such difficult to use plain javascript, for example,

use

    document.querySelector('#reminders-modal').remove()

instead of

    $('#reminders-modal').remove()

You could find many examples in [this commit](https://github.com/brookhong/Surfingkeys/commit/45dd0c37a3096c3ddd18e6216791176f007d40cb)
