### ISSUE TITLE
Scrolling not working as expected on reddit

### ISSUE THREAD

**Issue by joshpurvis** [brookhong/Surfingkeys#811]
## Error details

SurfingKeys: 0.9.37

Browser: Chromium 68.0.3440.75 (Official Build) Manjaro Linux (64-bit)

URL: https://www.reddit.com (and then click on any comment thread)

## Context

When clicking on a comment thread in the new version of reddit, it creates some sort of floating `div` of the post on top of the main site. If you try scrolling with `j` or `k` it scrolls the main page in the background, but not the current thread you're read

Edit: the same thing appears to happen on twitter, though I don't use twitter regularly so doesn't really affect me.

**Comment by williamconnolly** [comment]
I checked on OS X and have a similar issue, but not exactly the same symptoms. This issue still deserves investigation, but I don't think it's feasible to fix it on the Surfingkeys side of things - the design of the new Reddit is multilayered and difficult to interact with.

In the short term I'd recommend disabling the new skin from your /prefs page, and installing Reddit Enhancement Suite. Some of the  key bindings clash, but they're easily remappable. I have a nasty feeling Reddit will force this awful redesign on us eventually though, so this is not a permanent solution.

**Comment by brookhong** [comment]
In a nutshell, use `cs` to change scroll target, then scroll.

That's because Reddit does not actually open a new page for the thread you just clicked. Reddit does some trick here to popup the thread in a DIV. The referer page still lives background, and scrollable.

To verify that, use your mouse(sorry, you need it now) to click the gray background, you are back to the referer page.
![image](https://user-images.githubusercontent.com/288207/43649225-32445e30-976f-11e8-8ac2-dbf04a2236a7.png)

**Comment by joshpurvis** [comment]
(Sorry for the delay, I was on vacation.. )

@brookhong Thanks! `cs` is exactly what I was looking for, somehow I overlooked that in the list of shortcuts.

Would it be possible to put a rule in the advanced section, for something such as "https://www.reddit.com/r/*/comments/", which auto sets a specific source?

Also, could you point me to the code where the source is selected? Might hack around it, if I have some time..

Feel free to close this issue, `cs` shortcut is enough for me to get by when using my laptop.

**Comment by Jamie-505** [comment]
for me surfingkeys is not working at all on reddit... can't select links or switch tabs or anything else

**Comment by brookhong** [comment]
A new feature has been implemented in 0.9.49, which is to automatically focus a newly-created modal scrollable element. A thread on reddit is a typical case of this kind, a modal div is created on the page whenever you clicked on a thread's title, and the modal div is scrollable if there is enough content/comments in the thread. Surfingkeys will automatically set focus on this modal div, so that users need not to press `cs` to change scroll target in such case.
