### ISSUE TITLE
When displaying hints, open links in inactive new tab with Shift?

### ISSUE THREAD

**Issue by alaq** [brookhong/Surfingkeys#836]
When I show hints on a page, I do not know how many tabs I will open (one vs many). So I press `f` instead of `gf`. However, if I decide to open several links on the page, would it be possible to have `shift + [HINT]` open the link(s) in a new inactive tab?

I have temporarily remapped `f` to `gf`.

Is there a setting that I have missed to enable this? If not, is it something upi would be open to? Or would accept a PR for?

Thank you!

**Comment by codeanpeace** [comment]
Seconded! I'm in a similar boat where that's expected behavior from using Vimium on Chrome. It's to the point where that workflow of not deciding ahead of time aka whether to `f` or `gf` and relying on holding `shift + [HINT]` is muscle memory so I'm always surprised and frustrated at ending up needing to switch back tabs.
