### ISSUE TITLE
Lost configuration

### ISSUE THREAD

**Issue by xcv58** [brookhong/Surfingkeys#9]
I believe when the extension update, my configuration lost. Both local and sync.

**Comment by brookhong** [comment]
Sincerely sorry about that.

Yes, 0.2.0 made a big change to split default mappings from settings, so that user defined mappings can be preserved after extension upgraded.

The change is to avoid user's customization on mappings everytime after extension upgraded.

The default mappings are always created, so from now on, we need not keep default mappings in our own mappings, we just need to create customized mappings in settings.

* Create new mappings with `mapkey` as before, for example

        mapkey('c-y', 'Show me the money', function() {
            alert('a well-known phrase uttered by characters in the 1996 film Jerry Maguire');
        });

* Change keystroke for existing mappings with `map`, for example

        map('?', 'u');

* Remove existing mappings with `unmap`, for example

        unmap('c-i');

**Comment by xcv58** [comment]
Cool, thanks.

Another issue is that `space` shortcut is conflict with play/pause in some video player.

**Comment by brookhong** [comment]
`space` changed to `T` in default mappings.
