### ISSUE TITLE
[FEATURE REQUEST] Switch frame in the same way as link selection. 

### ISSUE THREAD

**Issue by yech1990** [brookhong/Surfingkeys#934]
`w` is for switch frames in the default setting of Surfingkeys.

There is three problems in real experience. 
- It is always difficult to tell which frame that the focus is in. 
- When there is too many frames in one page, it is waste lot of time to dump to the right one. 
- Some unscrollable element are misjudged. ([an example](https://download.lineageos.org/) )

`f` for url selection is a smart design. Will it be possible to adopt this feature into frame selection?
**Suppose when `w` is pressed, all the frames are highlighted with boarder and marked with text label. Users can select the exact frame they want quickly. Meanwhile, the current frame should be highlighted in different color.**  

**Please replace this with a description of how you were using SurfingKeys.**

**Comment by crocket** [comment]
When I choose a frame by selecting a frame hint, I don't want surfingkeys to scroll up or down.
Automatic scrolling often pushes the current visible region out of the view.

**Comment by aspiers** [comment]
This is a great idea.  I was just about to suggest the same.  It would also make sense to switch scroll target in the same way as link selection.

**Comment by brookhong** [comment]
The problem here is that there is only one frame in view in most cases, so hints to select frame might not make sense.

I'll make a change to current `w`, 

* if there are multiple frames in view, `w` will show hint for each of them, user then could use a hint to pick up one.
* if there is only one frame in view and the frame is not active, `w` will activate it.
* otherwise cycle to next frame in current window.

**Comment by aspiers** [comment]
sounds great!

**Comment by Shamaoke** [comment]
> if there are multiple frames in view, w will show hint for each of them, user then could use a hint to pick up one.
> if there is only one frame in view and the frame is not active, w will activate it.
> otherwise cycle to next frame in current window.

@brookhong Please, add an option to always show hints no matter how much of them on a page.

**Comment by desgua** [comment]
I made the following function that almost works as intended:

mapkey('a', '#2Focus top window', function() {
    top.focus();
    hints.create("iframe", function(element) {
    	console.log("hints.create");
        console.log("Hint created for iframe:", element);
        element.scrollIntoView({
            behavior: 'auto',
            block: 'center',
            inline: 'center'
        });
        normal.highlightElement(element);
        element.contentWindow.focus();
    });
});

The only problem is that we have to press the keybinding "a" twice because the first time we press "a" only "top.focus();" is executed, the second time we press "a" both "top.focus();" and "hints.create..." are executed.
